### ISSUE TITLE
REQUEST..to add files

### ISSUE THREAD

**Issue by SaikrishnaReddy1919** [Swetabhsuman8/Java-Basic-Codes-for-beginner-to-advance#1]
I have read your answer in Quora. I want to add some files which helps beginners to understand more about java. Check the example file below......

[Array.txt](https://github.com/Swetabhsuman8/Java-Basic-Codes-for-beginner-to-advance/files/2430526/Array.txt)

**Comment by SwetabhOfficial** [comment]
Hi Krishna,

Thank you so much for your contribution.
